"""add model rules

Revision ID: a6e0b52b68c3
Revises: 2349abc93b18
Create Date: 2025-12-03 17:00:42.255603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e0b52b68c3'
down_revision = '2349abc93b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Goal', sa.String(length=80), nullable=False),
    sa.Column('Rule_1', sa.String(length=120), nullable=False),
    sa.Column('Rule_2', sa.String(length=120), nullable=False),
    sa.Column('Rule_3', sa.String(length=120), nullable=False),
    sa.Column('Value', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule')
    # ### end Alembic commands ###
